// 塔罗牌完整数据库 - 78张
const TAROT_DECK = [
  // ==================== 大阿尔卡纳 (22张) ====================
  {
    id: 0, nameCn: '愚人', nameEn: 'The Fool', type: 'major', symbol: '🌄',
    upright: '新的开始、冒险精神、无限可能、天真率性、自由自在。你正站在一段全新旅程的起点，放下顾虑，勇敢迈出第一步。',
    reversed: '鲁莽冲动、犹豫不决、缺乏方向、逃避现实。你可能在逃避某个重要决定，或因为过于冲动而忽略了隐藏的风险。',
    keywords: ['开始', '自由', '冒险', '天真']
  },
  {
    id: 1, nameCn: '魔术师', nameEn: 'The Magician', type: 'major', symbol: '🪄',
    upright: '创造力、技能、意志力、行动力、资源齐备。你拥有一切所需的条件，只要善用手中的力量，就能将愿景化为现实。',
    reversed: '欺骗、能力不足、才能被浪费、无法掌控局面。需警惕表面华丽却缺乏实质的人或事，也可能暗示你尚未发挥真正潜力。',
    keywords: ['创造', '能力', '行动', '掌控']
  },
  {
    id: 2, nameCn: '女祭司', nameEn: 'The High Priestess', type: 'major', symbol: '🌙',
    upright: '直觉、智慧、神秘、内在感知、静待时机。相信你的直觉，答案不在外界而在内心深处，保持耐心和沉静。',
    reversed: '忽视直觉、情绪封闭、秘密被揭露、表面化。你可能在压抑自己的感受，或者过于依赖理性而忽略了内心的声音。',
    keywords: ['直觉', '智慧', '神秘', '等待']
  },
  {
    id: 3, nameCn: '女皇', nameEn: 'The Empress', type: 'major', symbol: '👑',
    upright: '丰饶、母性、孕育、自然之美、感官享受。创造力与生命力蓬勃绽放，拥抱美好事物，享受生活的富足与温暖。',
    reversed: '依赖过度、创造力枯竭、情感窒息、物质匮乏。提醒你关注自我照顾，不要因为照顾他人而耗尽自己的能量。',
    keywords: ['丰盛', '母性', '创造', '自然']
  },
  {
    id: 4, nameCn: '皇帝', nameEn: 'The Emperor', type: 'major', symbol: '🏰',
    upright: '权威、稳定、规则、领导力、秩序。建立稳固的基础，用理性和纪律掌控全局，展现坚定而可靠的领袖风范。',
    reversed: '专制、固执、权力滥用、缺乏自律。过度控制会让周围人窒息，也可能是你自己缺乏纪律导致局面混乱。',
    keywords: ['权威', '秩序', '领导', '稳定']
  },
  {
    id: 5, nameCn: '教皇', nameEn: 'The Hierophant', type: 'major', symbol: '📿',
    upright: '传统、信仰、导师指引、精神成长、仪式。遵循内在信念，寻求智者的教导，或在既定的体系内找到属于自己的位置。',
    reversed: '反传统、盲目跟从、信仰危机、被教条束缚。你可能需要打破旧有规范，用自己的方式去追寻真相，而非人云亦云。',
    keywords: ['传统', '指引', '信仰', '教导']
  },
  {
    id: 6, nameCn: '恋人', nameEn: 'The Lovers', type: 'major', symbol: '💕',
    upright: '爱情、结合、和谐、选择、价值观契合。一段深刻的关系或重大抉择摆在面前，听从内心真实的声音做出决定。',
    reversed: '分歧、背叛、错误选择、价值观冲突、分离。关系上的不和谐或面临艰难的取舍，需要诚实地面对自己真正的需求。',
    keywords: ['爱情', '选择', '和谐', '结合']
  },
  {
    id: 7, nameCn: '战车', nameEn: 'The Chariot', type: 'major', symbol: '🏆',
    upright: '胜利、意志力、突破阻碍、掌控方向、向前迈进。凭借坚定的决心和强大的自控力，你将战胜一切困难，驶向成功的彼岸。',
    reversed: '失控、挫败、方向迷失、内心冲突。你可能感到事情正在脱离掌控，或过于好胜导致身心俱疲，需要停下来重新校准方向。',
    keywords: ['胜利', '意志', '突破', '前进']
  },
  {
    id: 8, nameCn: '力量', nameEn: 'Strength', type: 'major', symbol: '🦁',
    upright: '勇气、内在力量、以柔克刚、耐心、自信。真正的力量来自内心的平静与慈悲，用温柔和毅力去驯服生命中的野兽。',
    reversed: '软弱、自我怀疑、失控、恐惧、滥用力量。你可能在质疑自己的能力，或因为内心的不安而表现出强势的外表。',
    keywords: ['勇气', '耐心', '内在', '柔韧']
  },
  {
    id: 9, nameCn: '隐士', nameEn: 'The Hermit', type: 'major', symbol: '🏮',
    upright: '内省、独处、寻求真理、深思熟虑、灵魂探索。退回到内在世界，在安静中照见生命的真相，让智慧之光指引前路。',
    reversed: '孤僻、逃避、拒绝指导、过度内耗。孤立自己并不能解决问题，你可能需要走出封闭，向外界寻求一些反馈和支持。',
    keywords: ['内省', '智慧', '独处', '探索']
  },
  {
    id: 10, nameCn: '命运之轮', nameEn: 'Wheel of Fortune', type: 'major', symbol: '🔮',
    upright: '命运转折、机遇、循环、运势上升、顺应变化。幸运之轮正在转动，把握当下的契机，顺势而为，迎接即将到来的转机。',
    reversed: '厄运、抵抗变化、轮回停滞、失控的变数。你可能正面临一段低谷期，但记住命运之轮不会永远停在底部，保持信心。',
    keywords: ['命运', '转折', '机遇', '循环']
  },
  {
    id: 11, nameCn: '正义', nameEn: 'Justice', type: 'major', symbol: '⚖️',
    upright: '公正、责任、平衡、真相、因果法则。种瓜得瓜，种豆得豆。以冷静客观的态度做出判断，承担起应有的责任。',
    reversed: '不公、逃避责任、偏见、失衡。你可能遇到了不公平的对待，或者自己在某些事情上未能做到诚实和公正。',
    keywords: ['公正', '责任', '真相', '平衡']
  },
  {
    id: 12, nameCn: '倒吊人', nameEn: 'The Hanged Man', type: 'major', symbol: '🙃',
    upright: '牺牲、换个角度、暂停、放下、顿悟。以全然的接纳面对当下的困境，换个视角看世界，在静默中孕育新的领悟。',
    reversed: '无谓牺牲、固执、停滞不前、错失机会。你可能在做无谓的等待或牺牲，需要重新审视是否值得继续坚持下去。',
    keywords: ['牺牲', '暂停', '视角', '领悟']
  },
  {
    id: 13, nameCn: '死神', nameEn: 'Death', type: 'major', symbol: '💀',
    upright: '结束、转变、重生、净化、放下过去。一个旧阶段终将落幕，为新的可能腾出空间。这并非终结，而是一场深刻的蜕变。',
    reversed: '抗拒改变、恐惧失去、停滞、消极等待。死死抓住即将终结的事物只会带来痛苦，与其抗拒，不如放手让生命自然流转。',
    keywords: ['结束', '转变', '重生', '放下']
  },
  {
    id: 14, nameCn: '节制', nameEn: 'Temperance', type: 'major', symbol: '🏺',
    upright: '调和、中庸、耐心、融合、疗愈。找到生活的平衡点，将不同的元素调和为和谐的乐章，让身心回归平静与从容。',
    reversed: '失衡、过度放纵、缺乏节制、急躁。你可能在某方面走入了极端，需要重新找回中道，避免过度消耗自己的身体和精神。',
    keywords: ['平衡', '调和', '耐心', '疗愈']
  },
  {
    id: 15, nameCn: '恶魔', nameEn: 'The Devil', type: 'major', symbol: '⛓️',
    upright: '束缚、欲望、物质主义、执念、阴暗面。看清是什么在困住你——是外部的枷锁，还是你甘愿被束缚的心？觉察即是解脱的开始。',
    reversed: '挣脱束缚、觉醒、找回力量、戒除成瘾。你开始意识到自己被什么限制了，并且愿意打破枷锁，重新掌控自己的人生。',
    keywords: ['束缚', '欲望', '执念', '觉醒']
  },
  {
    id: 16, nameCn: '高塔', nameEn: 'The Tower', type: 'major', symbol: '⚡',
    upright: '崩塌、剧变、真相暴露、打破幻象、觉醒。看似坚固的一切可能在瞬间倾覆，但这正是粉碎虚假、重建真诚的必经之路。',
    reversed: '逃避灾难、勉强维持、内在崩溃、恐惧改变。你也许在拼命维持摇摇欲坠的局面，但与其苦苦支撑，不如允许它自然倒塌重建。',
    keywords: ['剧变', '崩塌', '真相', '觉醒']
  },
  {
    id: 17, nameCn: '星星', nameEn: 'The Star', type: 'major', symbol: '✨',
    upright: '希望、信念、疗愈、灵感、宁静。暴风雨后最明亮的星光正在照耀你。保持信心，宇宙在为你铺路，内心充满宁静与希望。',
    reversed: '绝望、失去信心、灵感枯竭、自我否定。暂时的困顿让你看不到前方的光亮，但请相信黑暗只是黎明前的序曲。',
    keywords: ['希望', '疗愈', '信念', '灵感']
  },
  {
    id: 18, nameCn: '月亮', nameEn: 'The Moon', type: 'major', symbol: '🌑',
    upright: '幻象、恐惧、潜意识、直觉导航、深层情绪。穿过迷雾最好的方式是直面它。相信直觉为你指路，即使前路看来并不明朗。',
    reversed: '恐惧消散、真相浮现、自我欺骗被打破。迷雾正在散去，隐藏的真相逐渐浮出水面，焦虑和不安将慢慢得到释放。',
    keywords: ['幻象', '恐惧', '直觉', '潜意识']
  },
  {
    id: 19, nameCn: '太阳', nameEn: 'The Sun', type: 'major', symbol: '☀️',
    upright: '喜悦、成功、生命力、温暖、清晰。一切都沐浴在光明中，这正是享受成果、散发热情、与所爱之人共享幸福的美好时光。',
    reversed: '黯淡、短暂的挫折、活力不足、缺乏信心。云层暂时遮住了阳光，但这不会改变太阳始终存在的事实，保持乐观。',
    keywords: ['喜悦', '成功', '活力', '光明']
  },
  {
    id: 20, nameCn: '审判', nameEn: 'Judgement', type: 'major', symbol: '📯',
    upright: '觉醒、重生、内在召唤、清算、释怀。听到内心深处召唤的声音，回顾过往、从中汲取智慧，然后迈向更高的人生阶段。',
    reversed: '逃避召唤、自责、无法释怀、拖延清算。你也许在抗拒做出某个重要决定，或深陷过去的错误无法自拔，是时候放下包袱了。',
    keywords: ['觉醒', '重生', '召唤', '释怀']
  },
  {
    id: 21, nameCn: '世界', nameEn: 'The World', type: 'major', symbol: '🌍',
    upright: '圆满、完成、整合、成就、旅程的终点。一个完整的周期已经完成，你达成了目标，感觉与世界融为一体，享受这份圆满之喜。',
    reversed: '未完成、停滞、延迟满足、无法闭环。事情接近尾声但还有最后一步需要走，不要着急，踏实地完成最后的拼图。',
    keywords: ['圆满', '完成', '成就', '整合']
  },

  // ==================== 小阿尔卡纳 - 权杖 (Wands) ====================
  { id: 22, nameCn: '权杖ACE', nameEn: 'Ace of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: 'A',
    upright: '新行动、灵感迸发、热情启动、创造力萌芽。一个绝佳的时机已经到来，充满激情地去开启你想要的一切。',
    reversed: '延迟启动、缺乏动力、方向混乱、创意被扼杀。你也许有好的想法但迟迟无法付诸行动，先找回内心的热情。',
    keywords: ['启动', '灵感', '热情', '创造'] },
  { id: 23, nameCn: '权杖二', nameEn: 'Two of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: '2',
    upright: '规划、远见、决策、拓张版图。站在高处眺望远方，为未来做出深思熟虑的规划，世界尽在你的掌握。',
    reversed: '犹豫不决、计划搁浅、害怕未知、缺乏远见。你被眼前的细节困住了，需要跳出框架看待更宏大的图景。',
    keywords: ['规划', '远见', '决策', '展望'] },
  { id: 24, nameCn: '权杖三', nameEn: 'Three of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: '3',
    upright: '扩张、远航、合作、视野开阔。你的计划已经开始见效，现在是时候将眼光放得更远，探索未知的领域。',
    reversed: '阻碍、延迟、视野狭窄、合作破裂。扩张的步伐暂时受阻，回头审视计划的根基是否足够扎实。',
    keywords: ['扩张', '远航', '合作', '探索'] },
  { id: 25, nameCn: '权杖四', nameEn: 'Four of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: '4',
    upright: '庆祝、安定、和谐、归家。一段辛勤努力后迎来了收获与欢庆的时刻，享受生活中简单而真实的快乐。',
    reversed: '不安、庆祝延迟、家庭矛盾、缺乏归属感。原本期待的喜悦未能如期而至，也许需要你主动去创造温馨的氛围。',
    keywords: ['庆祝', '安定', '和谐', '归属'] },
  { id: 26, nameCn: '权杖五', nameEn: 'Five of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: '5',
    upright: '竞争、冲突、多元观点碰撞、挑战。不同意见的摩擦反而能激发更多可能，将竞争化为成长的动力。',
    reversed: '逃避冲突、内部消耗、恶性竞争、妥协。避免正面对抗并不会让问题消失，找到建设性的方式表达分歧。',
    keywords: ['竞争', '冲突', '挑战', '多元'] },
  { id: 27, nameCn: '权杖六', nameEn: 'Six of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: '6',
    upright: '胜利、认可、凯旋、自信。你的努力终获认可，昂首阔步接受众人的赞美吧，这是你应得的荣光。',
    reversed: '失败、不被认可、骄傲自大、昙花一现。成功可能短暂停留，或你过度在意别人的评价而失去了本心。',
    keywords: ['胜利', '认可', '荣耀', '自信'] },
  { id: 28, nameCn: '权杖七', nameEn: 'Seven of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: '7',
    upright: '坚守、防卫、勇气、面对挑战。你正站在高处守护自己的成果，即使面对多方压力，也要坚定地站稳脚跟。',
    reversed: '节节败退、无力守护、被动妥协、丧失立场。你可能感到自己快要顶不住了，但或许换个防守策略就会有转机。',
    keywords: ['坚守', '勇气', '防卫', '挑战'] },
  { id: 29, nameCn: '权杖八', nameEn: 'Eight of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: '8',
    upright: '迅速行动、消息飞来、势头正盛、旅行。事情正在高速运转，障碍已被清除，消息和机会如箭般飞来。',
    reversed: '延迟、停滞、沟通不畅、计划中断。事情突然慢了下来，这也许是一个让你停下来检查细节的善意提醒。',
    keywords: ['迅速', '消息', '前进', '旅行'] },
  { id: 30, nameCn: '权杖九', nameEn: 'Nine of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: '9',
    upright: '坚持、韧性、最后的考验、警觉。你已经历过诸多战斗，虽然疲惫但仍站得笔直。再坚持一下，胜利就在前方。',
    reversed: '放弃、精疲力竭、警惕过度、偏执。你太累了，过度的防备让周围人也感到紧张。适当休息也是一种战斗策略。',
    keywords: ['坚持', '韧性', '考验', '警觉'] },
  { id: 31, nameCn: '权杖十', nameEn: 'Ten of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: '10',
    upright: '负担、责任沉重、压力、全力以赴。你背负了太多责任，虽然辛苦，但终点已经不远，再加把劲跨过最后的距离。',
    reversed: '不堪重负、崩溃、学会放手、过度承担。该卸下一些不属于你的负担了，学会说"不"才能走得更远。',
    keywords: ['负担', '责任', '压力', '坚持'] },
  { id: 32, nameCn: '权杖侍从', nameEn: 'Page of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: 'P',
    upright: '探索、新消息、热情学徒、好奇心。内心燃烧着对新事物的渴望，勇敢地去探索未知，像孩子一样保持纯粹的热情。',
    reversed: '缺乏方向、拖延、不安、没有耐心。热情来得快去得也快，你需要在众多兴趣中找到一个真正值得深耕的方向。',
    keywords: ['探索', '热情', '消息', '好奇'] },
  { id: 33, nameCn: '权杖骑士', nameEn: 'Knight of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: 'Kt',
    upright: '冒险、行动、追逐梦想、勇气十足。这个骑士充满激情，一旦锁定目标就会飞驰而去，勇敢地追逐你心中的火焰。',
    reversed: '鲁莽、冲动、半途而废、急躁惹祸。速度太快反而容易摔倒，放慢脚步才能赢得持久之战。',
    keywords: ['冒险', '行动', '追逐', '勇气'] },
  { id: 34, nameCn: '权杖皇后', nameEn: 'Queen of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: 'Q',
    upright: '自信、魅力、领导力、温暖坚定。她像火焰一样耀眼而温暖，用自己的光芒照亮他人，展现出独立而充满魅力的姿态。',
    reversed: '暴躁、控制欲、自我怀疑、魅力黯淡。你可能正在经历一段不安的时期，嫉妒和过度控制反而让你失去真正的光芒。',
    keywords: ['自信', '魅力', '领导', '温暖'] },
  { id: 35, nameCn: '权杖国王', nameEn: 'King of Wands', type: 'minor', suit: 'wands',
    symbol: '🔥', rank: 'K',
    upright: '远见、领导、企业家精神、果敢。他是一位天生的领导者，用开阔的视野和坚定的行动力开创属于自己的事业版图。',
    reversed: '暴君、独断专行、目标过高、缺乏耐心。过高的期望和专横的态度会疏远身边的人，请记住真正的领导来自感召而非压制。',
    keywords: ['领导', '远见', '果敢', '开创'] },

  // ==================== 小阿尔卡纳 - 圣杯 (Cups) ====================
  { id: 36, nameCn: '圣杯ACE', nameEn: 'Ace of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: 'A',
    upright: '新感情、爱意涌现、直觉开启、丰沛情感。心中充满爱与喜悦，让情感如泉水般自然流淌，迎接一段新的关系或创作。',
    reversed: '情感压抑、空虚、爱被拒绝、创造力枯竭。你可能正在关闭自己的心门，给情感一个安全的出口比压抑更好。',
    keywords: ['爱', '情感', '直觉', '开始'] },
  { id: 37, nameCn: '圣杯二', nameEn: 'Two of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: '2',
    upright: '伴侣关系、平等交流、默契、彼此吸引。两颗心在和谐中靠近，无论是爱情还是合作都预示着美好的连接正在建立。',
    reversed: '关系破裂、不平等、分离、信任缺失。一段关系出现了裂痕，需要双方真诚面对问题，而非一厢情愿地维系表面和平。',
    keywords: ['伴侣', '平等', '连接', '吸引'] },
  { id: 38, nameCn: '圣杯三', nameEn: 'Three of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: '3',
    upright: '欢庆、友情、团聚、分享喜悦。三五好友共聚一堂，庆祝生命中美好的时刻。这是属于友谊和合作的欢乐时光。',
    reversed: '过度社交、流言、三人成虎、友情变味。聚会虽欢乐但不要忽视了真正重要的关系，小心表面的热闹掩盖了深层的裂痕。',
    keywords: ['欢庆', '友情', '团聚', '分享'] },
  { id: 39, nameCn: '圣杯四', nameEn: 'Four of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: '4',
    upright: '沉思、倦怠、不满、错失机会。你正沉浸在内心世界中，或许对眼前的一切感到乏味。但别忘了低头看看，新的机会也许正在脚边。',
    reversed: '跳出倦怠、新动机、抓住机会、觉醒。你终于从沉闷中抬起头来，开始注意到那些被你忽略的机会和生活的新方向。',
    keywords: ['沉思', '倦怠', '不满', '机会'] },
  { id: 40, nameCn: '圣杯五', nameEn: 'Five of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: '5',
    upright: '失落、遗憾、哀悼、聚焦失去。你正为倒掉的杯子感到悲伤，但别忘了身后还有两个杯子仍然完好地立在那里。',
    reversed: '走出悲伤、接受、重建、看到希望。你开始从失落中走出来，接纳现实并重新发现生活中依然美好的那一面。',
    keywords: ['失落', '遗憾', '哀悼', '接受'] },
  { id: 41, nameCn: '圣杯六', nameEn: 'Six of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: '6',
    upright: '怀旧、童年、纯真、给予。美好的回忆带给你温暖，或是一位故人重现在你的生活中，重新感受简单纯粹的快乐。',
    reversed: '沉溺过去、无法成长、停滞、被往事困住。过度怀旧让你忽略了当下的美好，向前走并不意味着遗忘。',
    keywords: ['怀旧', '纯真', '回忆', '给予'] },
  { id: 42, nameCn: '圣杯七', nameEn: 'Seven of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: '7',
    upright: '幻想、多重选择、想象力、白日梦。诸多诱人的选择摆在面前，但并非所有都是真实可行的。用理性分辨哪一个是真正的方向。',
    reversed: '清晰、下定决心、幻象消散、聚焦。你拨开了迷雾，看清了真正重要的选项，是时候做出具体的决定了。',
    keywords: ['幻想', '选择', '梦想', '分辨'] },
  { id: 43, nameCn: '圣杯八', nameEn: 'Eight of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: '8',
    upright: '离去、寻找意义、放下、踏上精神之旅。你决定离开熟悉但没有满足感的环境，踏上一条寻找更深层次意义的路。',
    reversed: '徘徊、舍不得离开、恐惧未知、回心转意。你犹豫是否该转身离去，内心的牵绊让你无法完全割舍。',
    keywords: ['离去', '寻找', '放下', '远行'] },
  { id: 44, nameCn: '圣杯九', nameEn: 'Nine of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: '9',
    upright: '愿望成真、满足、幸福、享受。你内心深处的愿望正在实现，坐在丰盛之中，享受这份来自努力和运气的满足感。',
    reversed: '愿望落空、内心空虚、表面满足、不满。光鲜的外表可能掩盖了内在的空洞，问问自己真正需要的是什么。',
    keywords: ['愿望', '满足', '幸福', '享受'] },
  { id: 45, nameCn: '圣杯十', nameEn: 'Ten of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: '10',
    upright: '圆满家庭、幸福、和谐、终极满足。情感的圆满达到巅峰，家人和睦、内心充盈，这正是你一直向往的美好状态。',
    reversed: '家庭不和、幸福破碎、理想破灭、疏离。表面的完美家庭可能藏着未被解决的问题，需要坦诚沟通来修复裂痕。',
    keywords: ['圆满', '家庭', '幸福', '和谐'] },
  { id: 46, nameCn: '圣杯侍从', nameEn: 'Page of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: 'P',
    upright: '创意萌芽、直觉消息、浪漫情怀、艺术灵感。一个充满想象力和温柔情感的人或消息正在靠近，保持心灵的开放和柔软。',
    reversed: '情感不成熟、过度理想化、创意受阻、逃避现实。你的梦想可能脱离了现实基础，先学会脚踏实地地表达情感。',
    keywords: ['创意', '直觉', '浪漫', '灵感'] },
  { id: 47, nameCn: '圣杯骑士', nameEn: 'Knight of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: 'Kt',
    upright: '浪漫追求、理想主义、求婚、艺术表达。优雅而浪漫的骑士带着真挚的情感前来，去追求你内心真正热爱的人或事吧。',
    reversed: '情感幻想、不切实际、夸大、情绪起伏。浪漫过头容易变得不切实际，小心那些只给你画饼而不付诸行动的人。',
    keywords: ['浪漫', '理想', '追求', '优雅'] },
  { id: 48, nameCn: '圣杯皇后', nameEn: 'Queen of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: 'Q',
    upright: '温柔、同理心、直觉力、情感滋养。她像水一样包容而深刻地理解他人，用温柔的力量抚慰着每一个受伤的灵魂。',
    reversed: '情绪依赖、过度敏感、自怜、内在空虚。你可能因为过于在意他人的情绪而耗尽了自己，请先照顾好自己的心。',
    keywords: ['温柔', '同理', '直觉', '滋养'] },
  { id: 49, nameCn: '圣杯国王', nameEn: 'King of Cups', type: 'minor', suit: 'cups',
    symbol: '💧', rank: 'K',
    upright: '情感成熟、包容、艺术修养、沉稳的爱心。他深谙情感的智慧，能够在情感的波涛中保持从容，用温柔而坚定的方式领导他人。',
    reversed: '情绪失控、隐藏脆弱、操纵情感、冷漠。表面上波澜不惊但内心可能暗潮汹涌，学会健康地表达自己的脆弱。',
    keywords: ['成熟', '包容', '沉稳', '艺术'] },

  // ==================== 小阿尔卡纳 - 宝剑 (Swords) ====================
  { id: 50, nameCn: '宝剑ACE', nameEn: 'Ace of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: 'A',
    upright: '清晰思维、真理、突破、决断力。如利剑般斩开迷雾，一个清晰的念头或真相降临，帮助你做出果断的决策。',
    reversed: '混乱思维、谎言、错误判断、暴力。信息可能被扭曲，或你的判断受到了偏见的影响，不要急于下结论。',
    keywords: ['清晰', '真理', '决断', '突破'] },
  { id: 51, nameCn: '宝剑二', nameEn: 'Two of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: '2',
    upright: '抉择僵局、平衡两难、闭眼逃避、内心拉锯。面对两个选项你选择了闭上眼睛，但逃避并不能让抉择消失。',
    reversed: '打破僵局、抉择浮现、真相披露。你终于愿意面对那个让你两难的问题了，摘下蒙眼的布，看清楚再行动。',
    keywords: ['抉择', '僵局', '逃避', '平衡'] },
  { id: 52, nameCn: '宝剑三', nameEn: 'Three of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: '3',
    upright: '心碎、悲伤、背叛、失落。三把剑刺穿心脏，痛苦如此清晰而真实。允许自己感受这份悲伤，它是疗愈的开始。',
    reversed: '走出悲伤、释怀、愈合、放下。伤口正在慢慢愈合，虽然疤痕还在，但你已经有力量继续前进了。',
    keywords: ['心碎', '悲伤', '失落', '疗愈'] },
  { id: 53, nameCn: '宝剑四', nameEn: 'Four of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: '4',
    upright: '休息、冥想、恢复、暂停战斗。你需要一段安静的时光来恢复精力，暂时从纷乱的思绪中抽离，让身心休息。',
    reversed: '重返战斗、精力恢复、无法安宁、催促自己。休息已经足够，是时候重新站起来面对挑战了。但也可能提醒你休息得还不够。',
    keywords: ['休息', '冥想', '恢复', '暂停'] },
  { id: 54, nameCn: '宝剑五', nameEn: 'Five of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: '5',
    upright: '争执、胜利但代价、冲突升级、不光彩的赢。你或许赢得了争论却输了关系。这场胜利真的值得吗？',
    reversed: '和解、修复、放下争执、走出冲突。过去的恩怨正在消散，你愿意伸出橄榄枝，寻求和解的新可能。',
    keywords: ['争执', '代价', '冲突', '输赢'] },
  { id: 55, nameCn: '宝剑六', nameEn: 'Six of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: '6',
    upright: '过渡、离开困境、向前迈进、疗愈之旅。你正在从一个艰难时期过渡到更平静的水域，虽然缓慢但方向正确。',
    reversed: '无法离开、陷入困境、拒绝帮助、回到过去。你可能被困在原地了，或者内心不愿意真正放下过去向前走。',
    keywords: ['过渡', '离开', '疗愈', '前进'] },
  { id: 56, nameCn: '宝剑七', nameEn: 'Seven of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: '7',
    upright: '策略、隐秘行动、机智、独行。有时需要灵活运用策略来达成目标，但要确保你的行为经得起日后的审视。',
    reversed: '暴露、计划泄露、自欺欺人、诡计失策。你的小聪明将被揭穿，与其继续遮掩，不如坦诚面对一切。',
    keywords: ['策略', '隐秘', '机智', '谨慎'] },
  { id: 57, nameCn: '宝剑八', nameEn: 'Eight of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: '8',
    upright: '束缚、自我限制、被困、无力感。你觉得自己被四面困住了，但其实很多限制只存在于你的脑海中。先解开眼罩看看。',
    reversed: '挣脱束缚、自由、破除限制、找到出路。你开始意识到束缚的来源，只要有勇气迈出第一步，困境就能破除。',
    keywords: ['束缚', '限制', '被困', '觉醒'] },
  { id: 58, nameCn: '宝剑九', nameEn: 'Nine of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: '9',
    upright: '焦虑、噩梦、过度担忧、深夜恐惧。你的思绪正在深夜中无限放大恐惧，但这些灾难化的想象往往并非真实的未来。',
    reversed: '放下焦虑、曙光、寻求帮助、理性回归。最黑暗的夜终将过去，你开始从焦虑的漩涡中浮出水面，呼吸到新鲜的空气。',
    keywords: ['焦虑', '噩梦', '担忧', '恐惧'] },
  { id: 59, nameCn: '宝剑十', nameEn: 'Ten of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: '10',
    upright: '结束、最低点、彻底放下、绝境。这把牌看起来触目惊心，但它意味着最坏的时刻已经过去，从谷底只能向上。',
    reversed: '复苏、重生、拒绝结束、再次站起来。伤口在愈合，阳光重新照进生活，你从废墟中缓慢而坚定地重建自己。',
    keywords: ['结束', '谷底', '彻底', '重生'] },
  { id: 60, nameCn: '宝剑侍从', nameEn: 'Page of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: 'P',
    upright: '好奇心、求知、警觉、新想法。你渴望获取新知识，用敏锐的头脑观察周围的一切，保持开放但不过于轻信。',
    reversed: '八卦、精神懒惰、冷嘲热讽、自以为是。你以为自己知道一切，但其实还有很多需要学习的地方，保持谦虚。',
    keywords: ['好奇', '求知', '警觉', '新想法'] },
  { id: 61, nameCn: '宝剑骑士', nameEn: 'Knight of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: 'Kt',
    upright: '果断出击、快速行动、直接、锐气。如疾风般冲向目标的骑士，用精准的判断和迅速的行动打破一切障碍。',
    reversed: '鲁莽、冲动、不计后果、只说不做。速度虽快但方向可能全错了，放慢脚步思考一下再行动也不迟。',
    keywords: ['果断', '快速', '直接', '锐气'] },
  { id: 62, nameCn: '宝剑皇后', nameEn: 'Queen of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: 'Q',
    upright: '理性、独立、洞察力、清明判断。她以锐利的智慧和独立的姿态面对世界，用逻辑和清晰的边界保护自己和所爱之人。',
    reversed: '冷硬、刻薄、过度独立、情感关闭。当理性变得无情，你可能在推开那些想走近你的人，适时展现柔软并非软弱。',
    keywords: ['理性', '独立', '洞察', '清明'] },
  { id: 63, nameCn: '宝剑国王', nameEn: 'King of Swords', type: 'minor', suit: 'swords',
    symbol: '⚔️', rank: 'K',
    upright: '权威理性、公正、正直、逻辑驾驭。他以冷静和智慧掌控局势，在复杂的问题中保持清醒，做出最公正的裁决。',
    reversed: '滥用权威、冷酷无情、操控、偏见。当权威脱离了公正，就可能变成暴政。反思自己是否在利用权力压制他人。',
    keywords: ['权威', '公正', '逻辑', '正直'] },

  // ==================== 小阿尔卡纳 - 星币 (Pentacles) ====================
  { id: 64, nameCn: '星币ACE', nameEn: 'Ace of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: 'A',
    upright: '新财富、机会、稳定开始、实质回报。一个财务或事业上的新机遇出现在眼前，抓住它，这将带来持续而稳定的增长。',
    reversed: '错失机会、财务不稳、计划延迟、资源浪费。机会可能正在溜走，或你对眼前的机遇不够重视，重新评估一下你的资源。',
    keywords: ['财富', '机会', '稳定', '开始'] },
  { id: 65, nameCn: '星币二', nameEn: 'Two of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: '2',
    upright: '平衡、灵活、适应、多任务处理。你需要像杂耍一样平衡多个任务或财务状况，虽然忙碌但你有能力保持动态的平衡。',
    reversed: '失衡、财务混乱、超负荷、跌落。多重任务正在失控，你无法同时兼顾所有事情，必须分出优先级做出取舍。',
    keywords: ['平衡', '灵活', '适应', '多任务'] },
  { id: 66, nameCn: '星币三', nameEn: 'Three of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: '3',
    upright: '团队合作、精湛技艺、学习、打好基础。和可靠的伙伴一起打磨技能，每一步都走得扎实而认真，成果经得起检验。',
    reversed: '合作不睦、粗制滥造、缺乏进步、团队矛盾。工作质量可能因为团队内部的问题而下降，需要重新调整分工和沟通方式。',
    keywords: ['合作', '技艺', '学习', '基础'] },
  { id: 67, nameCn: '星币四', nameEn: 'Four of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: '4',
    upright: '守财、稳固、节俭、控制。你对资源和金钱紧紧抓住不放，这带来了安全感，但也可能让你变得吝啬和封闭。',
    reversed: '放手、消费、分享、释放。你开始放下一味守财的心态，让金钱和资源流动起来，发现分享其实并不会让你失去什么。',
    keywords: ['守财', '稳固', '控制', '节俭'] },
  { id: 68, nameCn: '星币五', nameEn: 'Five of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: '5',
    upright: '困苦、匮乏、被排斥、求援。你可能正经历一段物质或精神上的匮乏期，但记住你并不孤单，伸出双手寻求帮助。',
    reversed: '走出困境、回归、找到归属、逆境反转。艰难的日子正在过去，重新找到工作和生活的锚点，温暖和希望正在回归。',
    keywords: ['困苦', '匮乏', '求援', '逆境'] },
  { id: 69, nameCn: '星币六', nameEn: 'Six of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: '6',
    upright: '给予与接受、慷慨、分享、互惠。财富和资源在流转中产生价值。无论是付出还是接受，保持一颗感恩和公平的心。',
    reversed: '不平等、利用、施舍变味、借贷失衡。给予和接受的关系失去了平衡，一方的过度索取或控制正在让这段关系变形。',
    keywords: ['给予', '接受', '慷慨', '互惠'] },
  { id: 70, nameCn: '星币七', nameEn: 'Seven of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: '7',
    upright: '等待收获、耐心、评估、长期投资。你播下的种子正在成长，现在需要耐心等待。回头检查一下，看看哪里需要调整。',
    reversed: '收成不佳、浪费时间、不耐烦、投资失误。你可能对缓慢的进展感到沮丧，或者意识到某些投入并没有产生应有的回报。',
    keywords: ['等待', '耐心', '收获', '评估'] },
  { id: 71, nameCn: '星币八', nameEn: 'Eight of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: '8',
    upright: '精进、工匠精神、勤奋、专注打磨。日复一日地专注于技能的磨练，每一个细小的进步都在为将来的卓越奠定基础。',
    reversed: '粗心大意、缺乏动力、工作倦怠、学艺不精。你在重复中失去了兴趣和专注，也许需要找到新的挑战来重新点燃热情。',
    keywords: ['精进', '工匠', '勤奋', '专注'] },
  { id: 72, nameCn: '星币九', nameEn: 'Nine of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: '9',
    upright: '自给自足、优雅、独立、享受。你靠自己的努力换来了舒适的生活，在属于自己的花园中悠然自得，享受这份独立带来的喜悦。',
    reversed: '依赖、奢华成性、孤独成功、失去根基。表面的享乐可能掩盖了深层的不安全感，或在独立的同时感到了深深的孤独。',
    keywords: ['自足', '优雅', '独立', '享受'] },
  { id: 73, nameCn: '星币十', nameEn: 'Ten of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: '10',
    upright: '财富传承、家族繁荣、长久稳定、终极富足。物质与家族的繁荣达到了顶峰，你不仅为自己，也为后代创造了稳固的根基。',
    reversed: '家族纷争、财产纠纷、传统丧失、不稳定。稳固的外表下可能存在家族内部的矛盾和金钱纠纷，需要透明的沟通来解决。',
    keywords: ['传承', '家族', '稳定', '富足'] },
  { id: 74, nameCn: '星币侍从', nameEn: 'Page of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: 'P',
    upright: '学习、务实、新技能、脚踏实地。带着对知识的渴望认真钻研，每一步都走得踏实而专注，为未来打下坚实的基础。',
    reversed: '学习困难、拖延、目标模糊、缺乏务实。你拥有好学的态度却缺少行动的毅力，把计划拆成小步骤会更容易执行。',
    keywords: ['学习', '务实', '技能', '踏实'] },
  { id: 75, nameCn: '星币骑士', nameEn: 'Knight of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: 'Kt',
    upright: '踏实、可靠、持之以恒、稳步推进。虽然进度不快，但每一步都极其稳健。他代表了一个可靠而负责的人或做事方式。',
    reversed: '停滞、过度谨慎、沉闷、缺乏激情。保守到了极点就会变成停滞，你可能需要冒一点小风险来打破沉闷的局面。',
    keywords: ['踏实', '可靠', '恒心', '稳健'] },
  { id: 76, nameCn: '星币皇后', nameEn: 'Queen of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: 'Q',
    upright: '富足、务实、滋养、慷慨、善于经营。她优雅而实际，懂得如何将资源经营得井井有条，同时慷慨地与所爱之人分享。',
    reversed: '财务焦虑、过度掌控、不安全感、不懂得享受。对物质的安全感过度执着反而让你无法真正享受生活，适当放手才会更轻松。',
    keywords: ['富足', '务实', '滋养', '经营'] },
  { id: 77, nameCn: '星币国王', nameEn: 'King of Pentacles', type: 'minor', suit: 'pentacles',
    symbol: '🪙', rank: 'K',
    upright: '财富、稳健、事业有成、可靠的大家长。他是物质世界中最稳固的力量，象征着持久的成功和脚踏实地的经营智慧。',
    reversed: '拜金、保守固执、财富风险、不择手段。对金钱的过度追求可能导致道德滑坡，或因为过于保守错过了重要的机会。',
    keywords: ['财富', '稳健', '成功', '经营'] }
];

// 牌阵定义
const SPREADS = {
  single: {
    name: '单张指引',
    positions: ['今日指引'],
    count: 1
  },
  three: {
    name: '三牌阵',
    positions: ['过去', '现在', '未来'],
    count: 3
  },
  celticCross: {
    name: '凯尔特十字阵',
    positions: ['现状', '阻碍', '根源', '过去', '目标', '未来', '态度', '环境', '希望与恐惧', '最终结果'],
    count: 10
  }
};